name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    
    - name: Installing protoc-gen-go
      run: |
        go get -u google.golang.org/grpc
        go get -u google.golang.org/protobuf
        sudo apt install protobuf-compiler
        sudo apt install golang-goprotobuf-dev

        go get -u google.golang.org/protobuf/cmd/protoc-gen-go
        go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
        go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
        go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
    
    - name: Setup Environment
      run: |
        export GOROOT=/usr/local/go
        export GOPATH=$HOME/go
        export GOBIN=$GOPATH/bin
        export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN
        source ~/.bash_profile

    - name: Generating protos
      run: |
        protoc --go-grpc_out=. proto/proto.proto
        protoc --go_out=. proto/proto.proto

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  # some linters don't like generated files
  # golangci:
  #   name: lint
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/setup-go@v3
  #       with:
  #         go-version: 1.18
  #     - uses: actions/checkout@v3
  #     - name: golangci-lint
  #       uses: golangci/golangci-lint-action@v3
  #       with:
  #         version: latest
  #         args: --skip-dirs='parser/generated'
